// <auto-generated />
using System;
using BDP.Registry.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BDP.Registry.Persistence.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    partial class RegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Citation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CitationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("citation_type_id");

                    b.Property<string>("DOI")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("doi");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_citations");

                    b.HasIndex("CitationTypeId")
                        .HasDatabaseName("ix_citations_citation_type_id");

                    b.HasIndex("JournalId")
                        .HasDatabaseName("ix_citations_journal_id");

                    b.HasIndex("SourceVersionId")
                        .HasDatabaseName("ix_citations_source_version_id");

                    b.ToTable("citations", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.CitationAuthor", b =>
                {
                    b.Property<Guid>("CitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("citation_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.HasKey("CitationId", "AuthorId")
                        .HasName("pk_citation_authors");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_citation_authors_author_id");

                    b.ToTable("citation_authors", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.CitationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_citation_types");

                    b.ToTable("citation_types", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Download", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Format")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("format");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("notes");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("protocol");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_downloads");

                    b.HasIndex("SourceVersionId")
                        .HasDatabaseName("ix_downloads_source_version_id");

                    b.ToTable("downloads", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_journals");

                    b.ToTable("journals", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_source_entries");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_source_entries_organization_id");

                    b.HasIndex("ExternalId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_source_entries_external_id_organization_id");

                    b.ToTable("source_entries", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_metadata");

                    b.Property<string>("ExternalVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_version");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("SourceEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entry_id");

                    b.Property<Guid?>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_source_versions");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_source_versions_species_id");

                    b.HasIndex("SourceEntryId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_source_versions_source_entry_id_version");

                    b.ToTable("source_versions", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceVersionStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer")
                        .HasColumnName("download_count");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.HasKey("Id")
                        .HasName("pk_source_version_statistics");

                    b.HasIndex("SourceVersionId")
                        .HasDatabaseName("ix_source_version_statistics_source_version_id");

                    b.ToTable("source_version_statistics", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceVersionTag", b =>
                {
                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("SourceVersionId", "TagId")
                        .HasName("pk_source_version_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_source_version_tags_tag_id");

                    b.ToTable("source_version_tags", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Citation", b =>
                {
                    b.HasOne("BDP.Registry.Persistence.Entities.CitationType", "CitationType")
                        .WithMany()
                        .HasForeignKey("CitationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_citations_citation_types_citation_type_id");

                    b.HasOne("BDP.Registry.Persistence.Entities.Journal", "Journal")
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_citations_journals_journal_id");

                    b.HasOne("BDP.Registry.Persistence.Entities.SourceVersion", "SourceVersion")
                        .WithMany("Citations")
                        .HasForeignKey("SourceVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_citations_source_versions_source_version_id");

                    b.Navigation("CitationType");

                    b.Navigation("Journal");

                    b.Navigation("SourceVersion");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.CitationAuthor", b =>
                {
                    b.HasOne("BDP.Registry.Persistence.Entities.Author", "Author")
                        .WithMany("Citations")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_citation_authors_authors_author_id");

                    b.HasOne("BDP.Registry.Persistence.Entities.Citation", "Citation")
                        .WithMany("Authors")
                        .HasForeignKey("CitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_citation_authors_citations_citation_id");

                    b.Navigation("Author");

                    b.Navigation("Citation");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Download", b =>
                {
                    b.HasOne("BDP.Registry.Persistence.Entities.SourceVersion", "SourceVersion")
                        .WithMany("Downloads")
                        .HasForeignKey("SourceVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_downloads_source_versions_source_version_id");

                    b.Navigation("SourceVersion");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceEntry", b =>
                {
                    b.HasOne("BDP.Registry.Persistence.Entities.Organization", "Organization")
                        .WithMany("SourceEntries")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_entries_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceVersion", b =>
                {
                    b.HasOne("BDP.Registry.Persistence.Entities.SourceEntry", "SourceEntry")
                        .WithMany("Versions")
                        .HasForeignKey("SourceEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_versions_source_entries_source_entry_id");

                    b.HasOne("BDP.Registry.Persistence.Entities.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_source_versions_species_species_id");

                    b.Navigation("SourceEntry");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceVersionStatistic", b =>
                {
                    b.HasOne("BDP.Registry.Persistence.Entities.SourceVersion", "SourceVersion")
                        .WithMany("Statistics")
                        .HasForeignKey("SourceVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_version_statistics_source_versions_source_version_id");

                    b.Navigation("SourceVersion");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceVersionTag", b =>
                {
                    b.HasOne("BDP.Registry.Persistence.Entities.SourceVersion", "SourceVersion")
                        .WithMany("Tags")
                        .HasForeignKey("SourceVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_version_tags_source_versions_source_version_id");

                    b.HasOne("BDP.Registry.Persistence.Entities.Tag", "Tag")
                        .WithMany("SourceVersions")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_version_tags_tags_tag_id");

                    b.Navigation("SourceVersion");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Author", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Citation", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Organization", b =>
                {
                    b.Navigation("SourceEntries");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceEntry", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.SourceVersion", b =>
                {
                    b.Navigation("Citations");

                    b.Navigation("Downloads");

                    b.Navigation("Statistics");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BDP.Registry.Persistence.Entities.Tag", b =>
                {
                    b.Navigation("SourceVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
